apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-master
  name: ms-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-master
  strategy: {}
  template:
    metadata:
      labels:
        app: ms-master
    spec:
      containers:
      - args:
        - ms_service_master
        image: mskube1
        name: master
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
        envFrom:
          - configMapRef:
              name: envs-config
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-master
  name: svc-master
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30080
  selector:
    app: ms-master
  type: NodePort
status:
  loadBalancer: {}